---
- name: "Raspberry PI4 Video Mixer Automation"
  hosts: localhost
  become: true
  connection: local
  gather_facts: true

  vars_prompt:

    - name: HOSTNAME
      prompt: "Hostname: "
      private: no
      default: "{{ lookup('pipe','raspi-config nonint get_hostname') }}"

    - name: TIMEZONE
      prompt: "Timezone: "
      private: no
      default: "{{ lookup('file', '/etc/timezone') }}"

    - name: LOCALE
      prompt: "LANG: "
      private: no
      default: "{{ lookup('env','LANG') }}"

    - name: ATEMIP
      prompt: "Atem mini IP: "
      private: no
      default: "{{ lookup('pipe','grep atem /etc/hosts | expand -t 1 | cut -f 1 -d \" \"') | default('192.168.2.240', true)  }}"

  vars:
    REBOOT: False
    UPDATE: False
    MEMSPLIT: "256"
    XKBLAYOUT: "us"
    NETNAMES: False
    BLUETOOTH: present # present or absent
    WIFI: present # present or absent
    WIFI_COUNTRY: "US"
    BOOTSPLASH: False
    OVERCLOCK: False
    HDMI_GROUP: 1
    HDMI_MOD: 34
    GLDRIVER: False
    raspiconfig:
      ssh: 0
      vnc: 1
      i2c: 1
      serial: 1
      onewire: 1
      rgpio: 1
      spi: 1
      boot_wait: 1
      overscan: 1
      camera: 1
      pixdub: 1
      blanking: 1

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      tags:
         - update

    - name: Upgrade apt packages
      apt: upgrade=dist force_apt_get=yes
      tags:
         - update

    - name: Installing Firmware packages
      apt:
        install_recommends: yes
        pkg:
        - rpi-eeprom
        - rpi-eeprom-images
      tags:
         - update

    - name: Update raspi-config itself
      become: true
      apt: name=raspi-config update_cache=yes state=present cache_valid_time=3600
      when: UPDATE == True
      tags:
         - update

    - name: raspi-config
      command: "raspi-config nonint do_{{ item.key }} {{ item.value }}"
      when: "item.value != lookup('pipe','sudo raspi-config nonint get_{{item.key}}')"
      with_dict: "{{ raspiconfig }}"
      tags:
        - raspi-config

    - name: Required Software
      apt:
        pkg:
        - git

    - name: Change hostname
      command: "raspi-config nonint do_hostname {{ HOSTNAME }}"
      when: lookup('pipe','raspi-config nonint get_hostname') != HOSTNAME
      tags:
         - raspi-config

    #N2 Wi-fi
    #- name: Set WiFi credentials
      #command: "raspi-config nonint do_wifi_ssid_passphrase {{ SSID }} {{ PASSPHRASE }}"
    
#    #N3 Network interface names
#    - name: Get network names status
#      command: "raspi-config nonint get_net_names"
#      register: pi_netnames
#      changed_when: False

#    - name: Print current network names status
#      debug:
#        msg: "Current network names status: {{ pi_netnames.stdout }}"

#    - name: Enable network names
#      command: "raspi-config nonint do_net_names 0"
#      when: (NETNAMES == True) and (pi_netnames.stdout != '0')

#    - name: Disable network names
#      command: "raspi-config nonint do_net_names 1"
#      when: (NETNAMES == True) and (pi_netnames.stdout != '1')

    - name: Set Boot behaviour
      command: "raspi-config nonint do_boot_behaviour B1"
      when: ( lookup('pipe','raspi-config nonint get_boot_cli') != "0" ) or
            ( lookup('pipe','raspi-config nonint get_autologin') != "1" )
      tags:
         - raspi-config

    - name: Change locale
      command: "raspi-config nonint do_change_locale {{ LOCALE }}"
      when: lookup('env','LANG') != LOCALE
      tags:
         - raspi-config

    - name: Change timezone
      command: "raspi-config nonint do_change_timezone {{ TIMEZONE }}"
      when: lookup('file', '/etc/timezone') != TIMEZONE
      tags:
         - raspi-config

#    #I3 Change Keyboard Layout
#    - name: Change keyboard layout
#      command: "raspi-config nonint do_configure_keyboard {{ XKBLAYOUT }}"

#    #I4 Change Wi-fi Country
#    - name: Get WiFi country
#      command: "raspi-config nonint get_wifi_country"
#      register: wifi_country
#      changed_when: False
#      ignore_errors: True #to avoid error when WiFi is not present
#
#    - name: Print current WiFi country
#      debug: 
#        msg: "Wifi country is: {{ wifi_country.stdout }}" 
#
#    #- name: Set WiFi country
#    #command: "raspi-config nonint do_wifi_country {{ WIFI_COUNTRY }}"

#6 Overclock

#    #A1 Expand Filesystem
#    - name: Check if FS is expandable
#      command: "raspi-config nonint get_can_expand"
#      register: fs_filled
#      changed_when: False

#    - name: Print if FS is expandable or not
#      debug:
#        msg: "Filesystem is expandable! [{{ fs_filled.stdout }}]"
#      when: fs_filled.stdout == '0'

    - name: Expand Filesystem
      command: "raspi-config nonint do_expand_rootfs"

    - name: Set GPU memory split
      command: "raspi-config nonint do_memory_split {{ MEMSPLIT }}"
      when: lookup('pipe','raspi-config nonint get_config_var gpu_mem /boot/config.txt') != MEMSPLIT
      tags:
         - raspi-config

#    ### 0 Auto, 1 Force 3.5mm, 2 Force hdmi
    - name: Set audio out
      command: "raspi-config nonint do_audio 1"
      tags:
         - raspi-config

    - name: Disable 4K 60fps
      command: "raspi-config nonint do_pi4video V3"
      when: lookup('pipe','raspi-config nonint get_pi4video') != "0"
      tags:
         - raspi-config

    - name: Set HDMI group mode
      command: "raspi-config nonint do_resolution {{ HDMI_GROUP }} {{ HDMI_MOD }}"
      when: ( lookup('pipe','raspi-config nonint get_config_var hdmi_group /boot/config.txt') != "1" ) or
            ( lookup('pipe','raspi-config nonint get_config_var hdmi_mode /boot/config.txt') != "34" )
      tags:
         - raspi-config

    - name: Enable HDMI audio
      lineinfile:
        path: /boot/config.txt
        line: 'hdmi_drive=2'
        regexp: "^#?hdmi_drive=."
        insertafter: "# DMT (computer monitor) modes"
        state: present
      when: lookup('pipe','raspi-config nonint get_config_var hdmi_drive /boot/config.txt') != "2"
      tags:
         - raspi-config

    - name: Real Clock CPU
      lineinfile:
        path: /boot/config.txt
        insertafter: '^#[all]'
        line: 'nohz=off'
        state: present
      tags:
         - raspi-config

    - name: WIFI
      lineinfile:
        path: /boot/config.txt
        insertafter: '^#[all]'
        line: 'dtoverlay=disable-wifi'
        regexp: "^#?dtoverlay=disable-wifi"
        state: present
      tags:
         - raspi-config

    - name: Bluetooth
      lineinfile:
        path: /boot/config.txt
        insertafter: '^#[all]'
        line: 'dtoverlay=pi3-disable-bt'
        regexp: "^#?dtoverlay=pi3-disable-bt"
        state: present
      tags:
         - raspi-config

    - name: CPU opts
      apt:
        pkg:
        - cpufrequtils

    - name: CPU performance
      lineinfile:
        path: /etc/default/cpufrequtils
        create: yes
        state: present
        line: 'GOVERNOR="performance"'

    - name: Reload CPU freq
      command: systemctl restart cpufrequtils

    - name: Disable console messages
      lineinfile:
        path: /etc/rc.local
        insertbefore: '^exit 0'
        line: 'dmesg --console-off'
        regexp: "^#?dmesg.--console-off$"
        state: present

    - name: Blank Console
      lineinfile:
        path: /etc/rc.local
        insertbefore: '^exit 0'
        line: '/usr/local/bin/clear-tty.sh &'
        regexp: "^#?\/usr\/local\/bin\/clear-tty.sh.&$"
        state: present

    - name: Blank Console script
      copy:
        dest: /usr/local/bin/clear-tty.sh
        create: yes
        group: root
        owner: root
        mode: '0755'
        content: |
          #!/bin/bash
          #

          sleep 10
          /usr/bin/clear > /dev/tty1
          exit 0

    - name: pi to sudo group
      user:
        name: pi
        groups: sudo
        append: yes

    # NOTE: Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
    - name: Passwordless sudo for pi user
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo.+ALL=.+$'
        line: '%sudo  ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

    - name: OMXD
      apt:
        pkg:
          - omxplayer
      tags:
        - omx

    - name: OMXD git
      git:
        repo: https://github.com/subogero/omxd.git
        dest: /usr/local/src/omxd
        force: yes
      tags:
        - omx

    - name: OMXD compile
      make:
        chdir: /usr/local/src/omxd
      tags:
        - omx

    - name: OMXD install
      make:
        chdir: /usr/local/src/omxd
        target: install
      tags:
        - omx

    - name: OMXD start
      make:
        chdir: /usr/local/src/omxd
        target: start
      tags:
        - omx

    - name: ATEM mini /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}.*atem$'
        line: "{{ ATEMIP }}\tatem"
        state: present
      tags:
         - companion

    - name: Download companion config
      get_url:
        url: https://github.com/robinhoodis/video_switcher/raw/master/videopi_full-config.companionconfig
        dest: /home/pi/videopi_full-config.companionconfig
        group: pi
        owner: pi
        mode: 0644
      tags:
         - companion

    - name: Put ATEM IP in companion config
      replace:
        path: /home/pi/videopi_full-config.companionconfig
        regexp: '"bmd-atem","product":"ATEM","label":"atem","_configIdx":0,"host":"(?:[0-9]{1,3}\.){3}[0-9]{1,3}"'
        replace: '"bmd-atem","product":"ATEM","label":"atem","_configIdx":0,"host":"{{ ATEMIP }}"'

    - name: Companion Dependencies
      apt:
        install_recommends: yes
        pkg:
        - libgusb-dev
        - nodejs
        - git
        - build-essential
        - cmake
        - libudev-dev
        - libusb-1.0-0-dev
      tags:
         - companion

    - name: Companion USB Dependencies
      copy:
        dest: /etc/udev/rules.d/50-companion.rules
        group: root
        owner: root
        mode: '0644'
        content: |
          SUBSYSTEM=="input", GROUP="input", MODE="0666"
          SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
          KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
          SUBSYSTEM=="usb", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f40", MODE:="666", GROUP="plugdev"
          KERNEL=="hidraw", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f40", MODE:="666", GROUP="plugdev"
          SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev"
          KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev"
          SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev"
          KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev"
          SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev"
          KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev"
          SUBSYSTEM=="usb", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f41", MODE:="666", GROUP="plugdev"
          KERNEL=="hidraw", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f41", MODE:="666", GROUP="plugdev"
      tags:
         - companion

    - name: Reload USB rules
      command: udevadm control --reload-rules
      tags:
         - companion

    - name: Update npm
      command: npm install n -g
      tags:
         - companion

    - name: Update node
      command: n 8.17.0
      tags:
         - companion

    - name: Install yarn
      command: npm install yarn -g
      tags:
         - companion

    - name: clone companion repo
      git:
         repo: https://github.com/bitfocus/companion.git
         dest: /usr/local/src/companion
         force: yes
      tags:
         - companion

    - name: Update companion modules - takes time....
      command:
        cmd: yarn update
        chdir: /usr/local/src/companion 
      environment:
        PATH: $HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:{{ ansible_env.PATH }}
      tags:
         - companion

    - name: Build writefile
      command: chdir=/usr/local/src/companion /usr/local/src/companion/tools/build_writefile.sh
      environment:
        PATH: $HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:{{ ansible_env.PATH }}
      tags:
         - companion

    - name: Companion USB Dependencies
      copy:
        dest: /etc/udev/rules.d/50-companion.rules
        group: root
        owner: root
        mode: '0644'
        content: |
          [Unit]
          Description=Bitfocus Companion (v2.0.0)
          After=network-online.target
          Wants=network-online.target

          [Service]
          Type=simple
          WorkingDirectory=/usr/local/src/companion
          ExecStart=/usr/local/src/companion/headless.js eth0
          Restart=on-failure
          KillSignal=SIGINT
          TimeoutStopSec=60

          [Install]
          WantedBy=multi-user.target
      tags:
         - companion

    - name: Companion config directory
      file:
       path: /usr/local/src/companion/undefined/companion/
       state: directory
       mode: 0755
       group: root
       owner: root
      tags:
         - companion

    - name: Create a symbolic link
      file:
        src: /home/pi/videopi_full-config.companionconfig
        dest: /usr/local/src/companion/undefined/companion/db
        force: yes
        owner: root
        group: root
        state: link
      tags:
         - companion

    - name: Start Companion
      systemd:
        name: companion.service
        state: restarted
        enabled: yes
      tags:
         - companion

    - name: Music Player
      apt:
        install_recommends: yes
        pkg:
          - mpd
          - mpc
      tags:
        - music

    - name: Configure MPD network
      lineinfile:
        path: /etc/mpd.conf
        state: present
        regexp: '^#?bind_to_address\s+\"(any|localhost)\"$'
        line: 'bind_to_address "any"'
      tags:
        - music

    - name: Configure MPD socket
      lineinfile:
        path: /etc/mpd.conf
        state: present
        regexp: '^#?bind_to_address\s+"/run/mpd/socket"$'
        line: 'bind_to_address "/run/mpd/socket"'
      tags:
        - music

    - name: Configure MPD 3.5mm output
      lineinfile:
        path: /etc/mpd.conf
        state: present
        regexp: '^#?\s+device\s+"hw:[0-1],0"\s+#\soptional$'
        line: '    device      "hw:1,0" # optional'
      tags:
        - music

#    - name: Softare volume out 3.5mm output
#      lineinfile:
#        backrefs: yes
#        path: /etc/mpd.conf
#        state: present
#        regexp: '^#?mixer_type\s+"(hardware|software)"\s+#\s+optional$'
#        line: '    mixer_type      "software" # optional'
#      tags:
#        - music

    - name: Configure Music Folder
      lineinfile:
        path: /etc/mpd.conf
        state: present
        regexp: '^#?music_directory.+".+"$'
        line: 'music_directory "/home/pi/Music"'
      tags:
        - music

    - name: Auto Start Music
      lineinfile:
        path: /etc/mpd.conf
        state: present
        regexp: '^#?restore_paused.+\"(yes|no)\"$'
        line: 'restore_paused "yes"'
      tags:
        - music

    - name: Configure Playlist Folder
      lineinfile:
        path: /etc/mpd.conf
        state: present
        regexp: '^#?playlist_directory.+".+"$'
        line: 'playlist_directory "/home/pi/Music"'
      tags:
        - music

    - name: Configure Playlist autoupdate
      lineinfile:
        path: /etc/mpd.conf
        state: present
        regexp: '^#?auto_update\s+"yes"$'
        line: 'auto_update "yes"'
      tags:
        - music

    - name: Start Music Player
      systemd:
        name: mpd
        enabled: yes
        state: started
      tags:
         - music

    - name: Filesharing
      apt:
        install_recommends: yes
        pkg:
        - netatalk
        - samba
        - samba-common-bin
      tags:
         - filesharing

    - name: Configure Netatalk Homes
      lineinfile:
        path: /etc/netatalk/afp.conf
        state: present
        regexp: '^; \[Homes\]$'
        line: '[Homes]'
      tags:
         - filesharing

    - name: Configure Netatalk /home
      lineinfile:
        path: /etc/netatalk/afp.conf
        state: present
        regexp: '^;.basedir.regex.=.\/xxxx$'
        line: 'basedir regex = /home'
      tags:
         - filesharing

    - name: Start Mac Filesharing
      systemd:
        name: netatalk
        enabled: yes
        state: started
      tags:
         - filesharing

    - name: Start Windows Filesharing
      systemd:
        name: smbd
        enabled: yes
        state: started
      tags:
         - filesharing

    - name: Convenient Tools
      apt:
        install_recommends: yes
        pkg:
        - vim
        - bash-completion
        - jq
        - speedtepst-cli
      tags:
        - userland

    - name: Creating .hushlogin inside users home
      become: False
      file:
        path: /home/pi/.hushlogin
        state: touch
        owner: pi
        group: pi
        mode: 0600
      tags:
         - userland

    - name: Alias vi to vim
      copy:
        dest: /etc/profile.d/vim.sh
        group: root
        owner: root
        mode: '0644'
        content: |
          alias vi=vim
      tags:
         - userland

    - name: pull vimrc from git
      become: False
      git:
        repo: https://github.com/amix/vimrc.git
        dest: /home/pi/.vim_runtime
        update: yes
        version: master
      tags:
         - userland

    - name: activate vimrc
      become: False
      command: chdir=/home/pi "/home/pi/.vim_runtime/install_awesome_vimrc.sh"
      tags:
         - userland

    - name: pull vim plugin for yml
      become: False
      git:
        repo: https://github.com/pearofducks/ansible-vim.git
        dest: /home/pi/.vim_runtime/my_plugins/ansible-vim
        update: yes
        version: master
      tags:
        - userland

    - name: update vim plugins
      become: False
      command:
        cmd: python update_plugins.py
        chdir: /home/pi/.vim_runtime
      tags:
         - userland

    - name: Reboot
      become: True
      command: "sleep 1 && shutdown -r now +1"
      async: 1
      poll: 0
      when: REBOOT == True

